{% set name = "pandoc" %}
{% set version = "2.4" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  # use GH to include functional upstream testing
  url: https://github.com/boisgera/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2d010068653c441eceb554ed83c7fc7d78a7fc13b9a90027abb4daed556d74df
  patches:
    - patches/0001-replace-strict-yaml.patch
    - patches/0001-skip-failures.patch

build:
  skip: True            # [s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - patch             # [not win]
    - m2-patch          # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - plumbum
    - ply
    - pandoc

test:
  imports:
    - pandoc
  commands:
    - pip check
    - python test.py -v
  requires:
    - python
    - pip
    - pyyaml
  source_files:
    - mkdocs/
    - mkdocs.yml
    - test.py

about:
  home: https://github.com/boisgera/pandoc
  doc_url: https://boisgera.github.io/pandoc
  dev_url: https://github.com/boisgera/pandoc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Pandoc Python Library brings Pandoc's document model to Python
  description: Pandoc is the awesome open-source command-line tool that converts documents from one format to another. 
    The project was initiated by John MacFarlane; under the hood, it's a Haskell library.
    The Pandoc Python Library brings Pandoc's document model to Python.

extra:
  recipe-maintainers:
    - mohamedlarbisentissi
